# Generated by Django 6.0.4 on 2026-04-09 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Référence')),
                ('niveau_entite', models.CharField(blank=True, choices=[('fidele', 'Fidèle'), ('eglise', 'Église Locale'), ('paroisse', 'Paroisse'), ('district', 'District'), ('region', 'Région'), ('national', 'National')], max_length=20)),
                ('entite_id', models.PositiveIntegerField(blank=True, null=True)),
                ('type_cotisation', models.CharField(choices=[('mensuelle_membre', 'Cotisation mensuelle membre'), ('dime', 'Dîme'), ('offrande', 'Offrande'), ('contribution_paroisse', 'Contribution Paroisse'), ('contribution_district', 'Contribution District'), ('contribution_region', 'Contribution Région'), ('cotisation_nationale', 'Cotisation Nationale'), ('don_special', 'Don Spécial'), ('projet', 'Projet Spécial')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('periode_mois', models.PositiveSmallIntegerField(blank=True, help_text='Mois concerné (1-12)', null=True)),
                ('periode_annee', models.PositiveSmallIntegerField(blank=True, help_text='Année concernée', null=True)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], default='especes', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID transaction Mobile Money')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('fidele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='members.fidele', verbose_name='Fidèle')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='ObjectifCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_entite', models.CharField(choices=[('fidele', 'Fidèle'), ('eglise', 'Église Locale'), ('paroisse', 'Paroisse'), ('district', 'District'), ('region', 'Région'), ('national', 'National')], max_length=20)),
                ('entite_id', models.PositiveIntegerField()),
                ('type_cotisation', models.CharField(choices=[('mensuelle_membre', 'Cotisation mensuelle membre'), ('dime', 'Dîme'), ('offrande', 'Offrande'), ('contribution_paroisse', 'Contribution Paroisse'), ('contribution_district', 'Contribution District'), ('contribution_region', 'Contribution Région'), ('cotisation_nationale', 'Cotisation Nationale'), ('don_special', 'Don Spécial'), ('projet', 'Projet Spécial')], max_length=30)),
                ('montant_objectif', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periode_mois', models.PositiveSmallIntegerField()),
                ('periode_annee', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Objectif de cotisation',
                'unique_together': {('niveau_entite', 'entite_id', 'type_cotisation', 'periode_mois', 'periode_annee')},
            },
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=20, unique=True)),
                ('genere_le', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='recus/')),
                ('cotisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu', to='contributions.cotisation')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
            },
        ),
    ]
