# Generated by Django 6.0.4 on 2026-04-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objectifcotisation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='churches.church', verbose_name='Église (tenant)'),
        ),
        migrations.AddField(
            model_name='objectifcotisation',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_cotisation', to='churches.church', verbose_name='Église (tenant)'),
        ),
        migrations.AddField(
            model_name='recu',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recus', to='churches.church', verbose_name='Église (tenant)'),
        ),
        migrations.AddConstraint(
            model_name='objectifcotisation',
            constraint=models.UniqueConstraint(fields=('church', 'niveau_entite', 'entite_id', 'type_cotisation', 'periode_mois', 'periode_annee'), name='contrib_objectif_church_periode_uniq'),
        ),
    ]
