# Generated by Django 6.0.4 on 2026-04-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='churches.church', verbose_name='Église'),
        ),
        migrations.AddField(
            model_name='user',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='churches.church', verbose_name='Église (tenant)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin_national', 'Administrateur National'), ('admin_region', 'Administrateur Régional'), ('superviseur_district', 'Superviseur de District'), ('chef_paroisse', 'Chef de Paroisse'), ('pasteur_local', 'Pasteur Local'), ('tresorier', 'Trésorier'), ('fidele', 'Fidèle')], default='fidele', max_length=30, verbose_name='Rôle'),
        ),
    ]
