# Generated by Django 6.0.4 on 2026-04-09 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('contenu', models.TextField()),
                ('niveau_visibilite', models.CharField(choices=[('national', 'National'), ('region', 'Région'), ('district', 'District'), ('paroisse', 'Paroisse'), ('eglise', 'Église Locale')], max_length=20)),
                ('entite_id', models.PositiveIntegerField(blank=True, null=True)),
                ('est_epingle', models.BooleanField(default=False, verbose_name='Épinglé')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-est_epingle', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.TextField(blank=True)),
                ('type_evenement', models.CharField(choices=[('convention', 'Convention'), ('conference', 'Conférence'), ('retraite', 'Retraite spirituelle'), ('culte_special', 'Culte spécial'), ('formation', 'Formation / Discipulat'), ('reunion', 'Réunion'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('lieu', models.CharField(blank=True, max_length=300, verbose_name='Lieu')),
                ('adresse', models.TextField(blank=True)),
                ('capacite_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité maximale')),
                ('niveau_visibilite', models.CharField(choices=[('national', 'National'), ('region', 'Région'), ('district', 'District'), ('paroisse', 'Paroisse'), ('eglise', 'Église Locale')], default='eglise', max_length=20)),
                ('entite_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'entité organisatrice")),
                ('inscription_requise', models.BooleanField(default=False, verbose_name='Inscription requise')),
                ('est_public', models.BooleanField(default=True, verbose_name='Visible par tous')),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('present', 'Présent')], default='en_attente', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='events.evenement')),
                ('fidele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_evenements', to='members.fidele')),
            ],
            options={
                'verbose_name': 'Inscription à un événement',
                'verbose_name_plural': 'Inscriptions aux événements',
                'ordering': ['-date_inscription'],
                'unique_together': {('evenement', 'fidele')},
            },
        ),
    ]
