# Generated by Django 6.0.4 on 2026-04-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='churches.church', verbose_name='Église (tenant)'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='churches.church', verbose_name='Église (tenant)'),
        ),
        migrations.AddField(
            model_name='inscriptionevenement',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_evenements', to='churches.church', verbose_name='Église (tenant)'),
        ),
    ]
