# Generated by Django 6.0.4 on 2026-04-09 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('info', 'Information'), ('alerte', 'Alerte'), ('rappel', 'Rappel'), ('succes', 'Succès')], default='info', max_length=20)),
                ('lien', models.CharField(blank=True, max_length=500, verbose_name='Lien de redirection')),
                ('est_lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
