# Generated by Django 6.0.4 on 2026-04-09 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='National',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'organisation")),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('date_fondation', models.DateField(blank=True, null=True, verbose_name='Date de fondation')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse du siège')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('description', models.TextField(blank=True)),
                ('couleur_primaire', models.CharField(default='#1e40af', max_length=7, verbose_name='Couleur primaire (hex)')),
                ('couleur_secondaire', models.CharField(default='#7c3aed', max_length=7, verbose_name='Couleur secondaire (hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation Nationale',
                'verbose_name_plural': 'Organisations Nationales',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='Code district')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du district')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('superviseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts_supervises', to=settings.AUTH_USER_MODEL, verbose_name='Superviseur de district')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Paroisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Code paroisse (3 chiffres)')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la paroisse')),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paroisses_dirigees', to=settings.AUTH_USER_MODEL, verbose_name='Chef de paroisse')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paroisses', to='hierarchy.district')),
            ],
            options={
                'verbose_name': 'Paroisse',
                'verbose_name_plural': 'Paroisses',
                'ordering': ['nom'],
                'unique_together': {('district', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Code région (2 lettres)')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la région')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='hierarchy.national')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions_dirigees', to=settings.AUTH_USER_MODEL, verbose_name='Responsable régional')),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='hierarchy.region'),
        ),
        migrations.CreateModel(
            name='EgliseLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Code église (3 chiffres)')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'église locale")),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('capacite', models.PositiveIntegerField(blank=True, null=True, verbose_name="Capacité d'accueil")),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pasteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eglises_dirigees', to=settings.AUTH_USER_MODEL, verbose_name='Pasteur / Responsable local')),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eglises', to='hierarchy.paroisse')),
            ],
            options={
                'verbose_name': 'Église Locale',
                'verbose_name_plural': 'Églises Locales',
                'ordering': ['nom'],
                'unique_together': {('paroisse', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'code')},
        ),
    ]
