# Generated by Django 6.0.4 on 2026-04-17 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
        ('hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='egliselocale',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='paroisse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='district',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='churches.church', verbose_name='Église (tenant)'),
        ),
        migrations.AddField(
            model_name='egliselocale',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eglises_locales', to='churches.church', verbose_name='Église (tenant)'),
        ),
        migrations.AddField(
            model_name='national',
            name='church',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='national_entity', to='churches.church', verbose_name='Église (tenant)'),
        ),
        migrations.AddField(
            model_name='paroisse',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paroisses', to='churches.church', verbose_name='Église (tenant)'),
        ),
        migrations.AddField(
            model_name='region',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='churches.church', verbose_name='Église (tenant)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=2, verbose_name='Code région (2 lettres)'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('region', 'code'), name='hierarchy_district_region_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='egliselocale',
            constraint=models.UniqueConstraint(fields=('paroisse', 'code'), name='hierarchy_eglise_paroisse_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='paroisse',
            constraint=models.UniqueConstraint(fields=('district', 'code'), name='hierarchy_paroisse_district_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('church', 'code'), name='hierarchy_region_church_code_uniq'),
        ),
    ]
