# Generated by Django 6.0.4 on 2026-04-09 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du ministère')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministeres', to='hierarchy.egliselocale')),
            ],
            options={
                'verbose_name': 'Ministère / Groupe',
                'verbose_name_plural': 'Ministères / Groupes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fidele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_fidele', models.CharField(editable=False, max_length=30, unique=True, verbose_name="Code d'identification")),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('genre', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], max_length=1, verbose_name='Genre')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=200, verbose_name='Lieu de naissance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fideles/photos/')),
                ('situation_familiale', models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], default='celibataire', max_length=20, verbose_name='Situation familiale')),
                ('nombre_enfants', models.PositiveSmallIntegerField(default=0, verbose_name="Nombre d'enfants")),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('telephone_2', models.CharField(blank=True, max_length=20, verbose_name='Téléphone secondaire')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('transfere', 'Transféré'), ('decede', 'Décédé')], default='actif', max_length=20)),
                ('date_inscription', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('date_bapteme', models.DateField(blank=True, null=True, verbose_name='Date de baptême')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fideles', to='hierarchy.egliselocale', verbose_name='Église locale')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fidele_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur lié')),
                ('ministeres', models.ManyToManyField(blank=True, related_name='membres', to='members.ministere', verbose_name='Ministères')),
            ],
            options={
                'verbose_name': 'Fidèle',
                'verbose_name_plural': 'Fidèles',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='TransfertFidele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateField(default=django.utils.timezone.now)),
                ('motif', models.TextField(blank=True, verbose_name='Motif du transfert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approuve_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_approuves', to=settings.AUTH_USER_MODEL)),
                ('eglise_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_entrants', to='hierarchy.egliselocale')),
                ('eglise_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_sortants', to='hierarchy.egliselocale')),
                ('fidele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='members.fidele')),
            ],
            options={
                'verbose_name': 'Transfert de fidèle',
                'verbose_name_plural': 'Transferts de fidèles',
                'ordering': ['-date_transfert'],
            },
        ),
    ]
