# Generated by Django 6.0.4 on 2026-04-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fidele',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fideles', to='churches.church', verbose_name='Église (tenant)'),
        ),
        migrations.AddField(
            model_name='ministere',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ministeres', to='churches.church', verbose_name='Église (tenant)'),
        ),
        migrations.AddField(
            model_name='transfertfidele',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferts_fideles', to='churches.church', verbose_name='Église (tenant)'),
        ),
    ]
